// This file is auto-generated by vite-plugin-pwa
// The service worker will be generated at build time by Workbox

// For development, you can test offline functionality manually
// The production build will include a fully functional service worker
// with caching strategies defined in vite.config.js

self.addEventListener('install', (event) => {
    console.log('Service Worker installing...');
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    console.log('Service Worker activating...');
    event.waitUntil(clients.claim());
});

// No token caching - per security spec
self.addEventListener('fetch', (event) => {
    // Let network requests pass through
    // Workbox will handle caching in production build
});
